### ISSUE TITLE
Binary exposure and Binary Outcome

### ISSUE THREAD

**Issue by coco40725** [tye27/mr.genius#1]
Sorry to bother you. I had the question about the code **mr.genius.R**.

In your paper, it seems that GENIUS-MAWII could be applied in binary exposure and binary outcome (if I didn't misunderstand something).

However, in this code, the function **mr.genius** seems only could be applied in continuous exposure and continuous outcome. 
Do I misunderstand something?  Can this function be applied directly in the scenario such that determining the causal effect of binary exposure on binary outcome? 

If not, do you have any suggestion that how I should modify the code to make this work?

**Comment by tye27** [comment]
Hi! Thanks for your question! What you said is correct, the current mr.genius package only applies to continuous exposure and continuous outcome. For Binary variables, we already know how to do estimation (briefly mentioned in the paper), but the inference part (i.e., how to calculate the standard error) is still under development. We will update the R package when we complete the theoretical developments.

**Comment by coco40725** [comment]
Okay, I got it! Thank you for your reply.   If it is okay, may I ask your opinion about determining the causal effect between binary variables?

So far as I know, GENIUS-MAWII is the novel  method developed based on **MR-GENIUS** (The GENIUS Approach to Robust Mendelian Randomization Inference), but GENIUS-MAWII's inference part for binary variables is still under development.  I was wondering if the inference part for binary variable in **MR-GENIUS** is finished.  

For **MR-GENIUS**, it seems that we can use **Multiplicative outcome model** to determine the causal effect of binary exposure on binary outcome. However, I didn't find out any simulation and real data application for this scenario.  Thus, I am not quite sure whether it is appropriate to use **MR-GENIUS** to determine the causal effect between two binary variables. Is it okay we could directly use the function **genius_mulY(Y,A,G)** (https://github.com/bluosun/MR-GENIUS) , where Y = Binary outcome; A = binary exposure; and G = SNPs (0,1,2) to determine the causal effect of binary exposure on binary outcome ?

Thank you for your help.

**Comment by tye27** [comment]
Hi!! Yes, you can use MR-GENIUS (and its R package) to determine the causal effect between two binary variables! GENIUS-MAWII is the extension of MR-GENIUS for many weak instruments.

**Comment by coco40725** [comment]
WOW!! Thank you very much! Really appreciate your helps!!!
